server:
  port: 9000
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8889/eureka}
spring:
  application:
    name: gatekeeper-server
  cloud:
    config:
      enabled: true
    stream:
      bindings:
        output:
          destination: user-registration
          content-type: application/json
          producer:
            partition-key-expression: payload.id
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
          zkNodes: localhost
          defaultZkPort: 2181
zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    registration-service: /registration/**
    search-service: /search/**