server:
  port: 9000
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8889/eureka}
signing:
  key: SomeRandomString
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: fooClientIdPassword
      client-secret: secret
      access-token-uri: http://localhost:9005/auth-server/oauth/token
      user-authorization-uri: http://localhost:9005/auth-server/oauth/authorize
    resource:
      user-info-uri: http://localhost:9005/auth-server/user
spring:
  application:
    name: gatekeeper-server
  zipkin:
    enabled: true
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1
  cloud:
    config:
      enabled: true
    stream:
      bindings:
        output:
          destination: user-registration
          content-type: application/json
          producer:
            partition-key-expression: payload.id
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
          zkNodes: localhost
          defaultZkPort: 2181
zuul:
  sensitive-headers: Cookie,Set-Cookie
  ignored-services: '*'
  prefix: /api
  routes:
    registration-service: /registration/**
    search-service: /search/**